name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Generate deployment package
      run: zip -r deploy.zip server simulator views package.json Dockerfile yarn.lock
      
    - name: Deploy to ElasticBeanstalk
      uses: einaregilsson/beanstalk-deploy@v3
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Green-Power
        environment_name: GreenPower-production
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip
